#!/usr/bin/env bash
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

func () {
    # Choose subdomain based on the passed argument
    if [ -z "$2" ]; # -z True if length of string "$2" is zero
    then
        subdomain=("www" "lb-01" "web-01" "web-02")
    else
        subdomain=("$2")
    fi

    for sub in "${subdomain[@]}"
    do
        # dig Domain and match pattern /ANS.../ then skip Matched line with getline
        # getline read the next input, skip matched /ANS.../ line and match next line
        recordtyp=$(dig "$sub.$1" | awk '/ANSWER SECTION:/{getline; print $4}')
        ipaddress=$(dig "$sub.$1" | awk '/ANSWER SECTION:/{getline; print $5}')
        echo "The subdomain $sub is a $recordtyp record and points to $ipaddress"
    done
}
# Calling function with arguments
func "$1" "$2"
