#!/usr/bin/env bash
# This script transfers a file from our client to a server.
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    # scp file($1) username($3)@ip($2):transfer to home directory (~/)
    # -o for ssh option --> Strict host disabled when using scp
    # -i for identity_file(private key --> $4)
    scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
fi
