#!/usr/bin/env bash
# This script configures a new Ubuntu machine.
sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" >  /var/www/html/index.nginx-debian.html

sudo service nginx restart
