#!/usr/bin/env bash
# Configure and install a new load balancer on server.


# First install load balancer HAproxy
apt-get update
apt-get install haproxy -y


# Configure HAproxy so that it send traffic to web-01 and web-02
echo "
frontend myfrontend
        bind *:80
        default_backend webservers

backend webservers
        balance roundrobin
        server 438055-web-01 100.26.246.92:80
        server 438055-web-02 54.237.124.240:80" >> /etc/haproxy/haproxy.cfg

# Make sure that HAproxy can be managed via an init script.
echo "ENABLED=1" >> /etc/default/haproxy

service haproxy start
