#!/usr/bin/env bash
# Configure and install a new load balancer on server.

# First install load balancer HAproxy
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.8 -y
apt-get install haproxy=2.8.\* -y

# Configure HAproxy so that it send traffic to web-01 and web-02

config_append="
frontend myfrontend
    bind *:80
    default_backend mywebservices

backend mywebservices
    balance roundrobin
    server 438055-web-01 18.207.142.229:80 check
    server 438055-web-02 54.90.27.197:80 check
"

echo "$config_append" | sudo tee -a /etc/haproxy/haproxy.cfg

# HAProxy will start at boot. 
# Make sure that HAproxy can be managed via an init script.
# Since we want the service to start automatically each time the server powers on

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
