#!/usr/bin/env bash
# -i for edit in place, s for string and g for golbal (all match)
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default # Replace all to 80
service nginx restart
kill -SIGKILL $(pgrep nginx | head -n 1) # Send kill signal <SIGKILL=9> for least process
