#!/usr/bin/env bash
# This script shows all processes, for all users.

ps axuf

# a list all processes
# x must have a tty including those which might not have a TTY
# u for user orianted format
# f show process hierarchy
