#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely with sleep 2 sec with tarps.

echo $$ > /var/run/myscript.pid

while true
do    
    trap "echo I hate the kill command &&
              rm /var/run/myscript.pid &&
                         exit" SIGTERM

    trap "echo Y U no love me?! && exit" SIGINT
    trap "rm /var/run/myscript.pid && exit" SIGQUIT

    echo 'To infinity and beyond'
    sleep 2
done
