#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely with sleep 2 sec with tarps.

echo $$ > /var/run/myscript.pid

while true
do    
    trap "echo I hate the kill command" SIGTERM 
    trap "echo Y U no love me?!" SIGINT
    trap "rm /var/run/myscript.pid" SIGQUIT SIGTERM 

    echo 'To infinity and beyond'
    sleep 2
done
