#!/usr/bin/env bash
# This script kill the process from the prevoius task.

kill "$(pgrep -f 4-to_infinity_and_beyond)"

# -f to match against the process name
# Remeber that pgrep return a `PID` of matched pattern you made
