#!/usr/bin/env bash
# This scirpt displays Best School 10 times with using for loop.

for ((i=0; i<10; i++))
do
    echo "Best School"
done

# OR
#
# for i in {0..10..1}
# do
#     echo "Best School"
# done

# OR
# for i in {0..10..1}; do echo "Best School"; done
