#!/usr/bin/env bash
# This script displays Best School 10 times using while loop.
# and print Hi at 9th loop

i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]; then
        echo "Hi"
    fi
    ((i++))
done
