#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.

i=0
while [ $i -le 20 ]; do
    echo "Hour $((i++)):"
    j=1
        while [ $j -lt 60 ]; do
            echo $((j++))
        done
done
