#!/usr/bin/bash
# Configure ufw so that it blocks all incoming traffic, except the following TCP ports

apt-get update
apt-get install ufw

ufw default deny incoming
ufw default allow outgoing

ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp

ufw enable
