#!/usr/bin/env bash
# This script config hosts file.

cp /etc/hosts ~/myhosts.new

# Replace line that start with 127
sed -i "s/^127.*$/127.0.0.2\tlocalhost\n8.8.8.8\t\tfacebook.com/" ~/myhosts.new

cp -f ~/myhosts.new /etc/hosts
