#!/usr/bin/env bash
# This script uses SSH client configuration
Host 54.89.109.180
    # Specifies a file from which the user's identity key is read
    # when using public xkey authentication
    IdentityFile ~/.ssh/school
    # Disable the password and passphrase
    PasswordAuthentication no 
